Working mnist model
You do need to manually edit the generated model:

let leading_dim = relu1_out1.shape().dims[..1].iter().product::<usize>()

becomes

let leading_dim = relu1_out1.shape().dims::<4>()[..1].iter().product::<usize>()

For more information about this error, try `rustc --explain E0616`.
error: could not compile `mamba-embedded` (lib) due to 1 previous error